include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false # we use debugPrint, but allow during early dev

analyzer:
  errors:
    invalid_annotation_target: ignore
